import { describe, expect, it } from 'vitest';
import {
  chooseDefaultWebVttSubtitle,
  deferredUpscaleLevelCap,
  parseWebVttCues,
  webVttCueTextAt,
} from './playback-runtime.js';

describe('playback runtime policy', () => {
  it('never auto-selects a burn-in subtitle and falls through to the next preferred WebVTT language', () => {
    expect(chooseDefaultWebVttSubtitle([
      { id: 'burnin-da', language: 'dan', label: 'Dansk PGS', delivery: 'burn_in' },
      { id: 'webvtt-en', language: 'eng', label: 'English', delivery: 'webvtt' },
    ], ['da', 'en'], 'auto')).toBe('webvtt-en');
  });

  it('selects forced WebVTT only in forced mode', () => {
    expect(chooseDefaultWebVttSubtitle([
      { id: 'normal-da', language: 'dan', label: 'Dansk', delivery: 'webvtt' },
      { id: 'forced-da', language: 'dan', label: 'Dansk forced', delivery: 'webvtt' },
    ], ['da'], 'forced')).toBe('forced-da');
  });

  it('prefers a complete subtitle over forced and SDH tracks in the same language', () => {
    expect(chooseDefaultWebVttSubtitle([
      { id: 'forced-da', language: 'dan', label: 'Dansk (tvungen)', delivery: 'webvtt' },
      { id: 'sdh-da', language: 'da', label: 'Dansk (hørehæmmede)', delivery: 'webvtt' },
      { id: 'full-da', language: 'da', label: 'Dansk', delivery: 'webvtt' },
    ], ['da'], 'auto')).toBe('full-da');
  });

  it('caps Auto at the highest native rendition until the upscale buffer gate opens', () => {
    expect(deferredUpscaleLevelCap([
      { height: 360, upscaled: false },
      { height: 720, upscaled: false },
      { height: 1080, upscaled: true },
    ], 720, true)).toBe(1);
    expect(deferredUpscaleLevelCap([
      { height: 720, upscaled: false },
    ], 720, true)).toBe(-1);
  });

  it('parses absolute WebVTT timestamps and renders against a resumed media timeline', () => {
    const cues = parseWebVttCues(`WEBVTT

00:00:03.000 --> 00:00:05.000
Local cue

01:00:09.500 --> 01:00:12.000 align:middle
<i>Fortsat cue &amp; tekst</i>`);

    expect(cues).toHaveLength(2);
    expect(webVttCueTextAt(cues, 3_610)).toBe('Fortsat cue & tekst');
    expect(webVttCueTextAt(cues, 3_609, -500)).toBe('Fortsat cue & tekst');
    expect(webVttCueTextAt(cues, 10)).toBe('');
  });

  it('ignores malformed cue blocks without discarding valid subtitles', () => {
    const cues = parseWebVttCues(`WEBVTT

NOTE generated by BoltBytes
not a cue

bad --> timestamp
ignored

00:01.000 --> 00:03.000
Gyldig tekst`);

    expect(cues).toEqual([{ startTimeSeconds: 1, endTimeSeconds: 3, text: 'Gyldig tekst' }]);
  });
});
