'use client';

import { CheckCircle2, Copy, Film, KeyRound, LoaderCircle, Plus, RefreshCw, SatelliteDish, Search, Server, Trash2, Tv, Webhook, XCircle } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api, type ApiFailure } from '@/lib/api';
import styles from './servarr-manager.module.css';

type Provider = 'sonarr' | 'radarr';
type Library = { id: string; name: string; type: string };
type Health = { online: boolean; instanceName?: string | null; version?: string | null; error?: string } | null;
type Connection = { provider: Provider; label: string; configured: boolean; enabled: boolean; url: string | null; libraryId: string | null; rootFolderPath: string | null; qualityProfileId: number | null; hasApiKey: boolean; hasWebhookSecret: boolean; webhookPath: string; health: Health; lastWebhook: { eventType: string; receivedAt: string; queuedScanId: string | null; title: string | null } | null };
type Overview = { canWrite: boolean; connections: Connection[]; libraries: Library[] };
type Resources = { rootFolders: { id: number; path: string; freeSpace: number | null; accessible: boolean }[]; qualityProfiles: { id: number; name: string }[]; queue: { count: number; unknownCount: number; errors: boolean } | null };
type Form = { url: string; apiKey: string; enabled: boolean; libraryId: string; rootFolderPath: string; qualityProfileId: string };
type Credentials = { webhookPath: string; username: string; password: string; headerName: string };
type Result = { provider: Provider; providerId: number; title: string; year: number | null; overview: string | null; existing: boolean; posterUrl: string | null };
const emptyForm: Form = { url: '', apiKey: '', enabled: true, libraryId: '', rootFolderPath: '', qualityProfileId: '' };

export function ServarrManager() {
  const [data, setData] = useState<Overview | null>(null); const [forms, setForms] = useState<Record<Provider, Form>>({ sonarr: emptyForm, radarr: emptyForm });
  const [resources, setResources] = useState<Partial<Record<Provider, Resources>>>({}); const [credentials, setCredentials] = useState<Partial<Record<Provider, Credentials>>>({});
  const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loaded, setLoaded] = useState(false);
  const [searchProvider, setSearchProvider] = useState<Provider>('sonarr'); const [term, setTerm] = useState(''); const [results, setResults] = useState<Result[]>([]);
  const load = useCallback(async () => { try { const next = await api<Overview>('/system/integrations/servarr'); setData(next); if (!loaded) { setForms(Object.fromEntries(next.connections.map((item) => [item.provider, { url: item.url ?? '', apiKey: '', enabled: item.enabled, libraryId: item.libraryId ?? '', rootFolderPath: item.rootFolderPath ?? '', qualityProfileId: item.qualityProfileId ? String(item.qualityProfileId) : '' }])) as Record<Provider, Form>); setLoaded(true); } } catch (reason) { setError(failure(reason)); } }, [loaded]);
  useEffect(() => { void load(); }, [load]);
  const connections = useMemo(() => Object.fromEntries((data?.connections ?? []).map((item) => [item.provider, item])) as Partial<Record<Provider, Connection>>, [data]);
  function update(provider: Provider, field: keyof Form, value: string | boolean) { setForms((current) => ({ ...current, [provider]: { ...current[provider], [field]: value } })); }
  async function run(name: string, task: () => Promise<void>) { setBusy(name); setMessage(''); setError(''); try { await task(); await load(); } catch (reason) { setError(failure(reason)); } finally { setBusy(''); } }
  async function loadResources(provider: Provider) { const next = await api<Resources>(`/system/integrations/servarr/${provider}/resources`); setResources((current) => ({ ...current, [provider]: next })); }
  async function save(provider: Provider) { const form = forms[provider]; await run(`save:${provider}`, async () => { const response = await api<Connection & { webhookCredentials: Credentials | null }>(`/system/integrations/servarr/${provider}`, { method: 'PUT', body: JSON.stringify({ url: form.url, ...(form.apiKey ? { apiKey: form.apiKey } : {}), enabled: form.enabled, ...(form.libraryId ? { libraryId: form.libraryId } : {}), ...(form.rootFolderPath ? { rootFolderPath: form.rootFolderPath } : {}), ...(form.qualityProfileId ? { qualityProfileId: Number(form.qualityProfileId) } : {}) }) }); if (response.webhookCredentials) setCredentials((current) => ({ ...current, [provider]: response.webhookCredentials! })); setForms((current) => ({ ...current, [provider]: { ...current[provider], apiKey: '' } })); setMessage(`${providerLabel(provider)} er valideret og gemt.`); await loadResources(provider); }); }
  async function test(provider: Provider) { const form = forms[provider]; await run(`test:${provider}`, async () => { const health = await api<Health>(`/system/integrations/servarr/${provider}/test`, { method: 'POST', body: JSON.stringify({ ...(form.url ? { url: form.url } : {}), ...(form.apiKey ? { apiKey: form.apiKey } : {}) }) }); setMessage(`${providerLabel(provider)} ${health?.version ?? ''} svarer korrekt.`); }); }
  async function rotate(provider: Provider) { await run(`rotate:${provider}`, async () => { const next = await api<Credentials>(`/system/integrations/servarr/${provider}/webhook-secret`, { method: 'POST' }); setCredentials((current) => ({ ...current, [provider]: next })); setMessage('Webhook-hemmeligheden er roteret. Den gamle virker ikke længere.'); }); }
  async function remove(provider: Provider) { if (!window.confirm(`Fjern ${providerLabel(provider)} og alle gemte credentials?`)) return; await run(`remove:${provider}`, async () => { await api(`/system/integrations/servarr/${provider}`, { method: 'DELETE' }); setForms((current) => ({ ...current, [provider]: emptyForm })); setResources((current) => ({ ...current, [provider]: undefined })); setCredentials((current) => ({ ...current, [provider]: undefined })); setMessage(`${providerLabel(provider)} er fjernet.`); }); }
  async function search() { if (term.trim().length < 2) return; await run('search', async () => { setResults(await api<Result[]>(`/system/integrations/servarr/${searchProvider}/lookup?term=${encodeURIComponent(term.trim())}`)); }); }
  async function add(item: Result) { await run(`add:${item.providerId}`, async () => { await api(`/system/integrations/servarr/${item.provider}/items`, { method: 'POST', body: JSON.stringify({ providerId: item.providerId, searchOnAdd: true, monitored: true }) }); setResults((current) => current.map((entry) => entry.providerId === item.providerId ? { ...entry, existing: true } : entry)); setMessage(`${item.title} er tilføjet og søgning er startet.`); }); }

  return <section className={styles.page}>
    <header className={styles.hero}><div><span>SERVARR AUTOMATION</span><h1>Sonarr & Radarr</h1><p>Forbind ønskelisten med downloaderen og lad afsluttede imports starte præcise BoltBytes-scans.</p></div><button onClick={() => void load()} disabled={Boolean(busy)}><RefreshCw />Opdatér status</button></header>
    {error && <p className={styles.error}><XCircle />{error}</p>}{message && <p className={styles.success}><CheckCircle2 />{message}</p>}
    <div className={styles.providers}>{(['sonarr', 'radarr'] as Provider[]).map((provider) => <ProviderCard key={provider} provider={provider} connection={connections[provider]} form={forms[provider]} libraries={data?.libraries ?? []} resources={resources[provider]} credentials={credentials[provider]} busy={busy} canWrite={data?.canWrite ?? false} update={update} save={save} test={test} loadResources={loadResources} rotate={rotate} remove={remove} />)}</div>
    <section className={styles.discovery}><header><div><SatelliteDish /><span><strong>Tilføj til automation</strong><small>Søg direkte i providerens officielle lookup og start overvågning med de gemte defaults.</small></span></div><div className={styles.search}><select value={searchProvider} onChange={(event) => { setSearchProvider(event.target.value as Provider); setResults([]); }}><option value="sonarr">Serier via Sonarr</option><option value="radarr">Film via Radarr</option></select><input value={term} onChange={(event) => setTerm(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void search(); }} placeholder="Søg efter titel eller provider-id" /><button onClick={() => void search()} disabled={!data?.canWrite || busy === 'search' || term.trim().length < 2}>{busy === 'search' ? <LoaderCircle className={styles.spin} /> : <Search />}Søg</button></div></header>
      <div className={styles.results}>{results.map((item) => <article key={`${item.provider}:${item.providerId}`}><div className={styles.poster}>{item.posterUrl ? <img src={item.posterUrl} alt="" /> : item.provider === 'sonarr' ? <Tv /> : <Film />}</div><div><span>{item.year ?? 'År ukendt'} · {providerLabel(item.provider)}</span><h3>{item.title}</h3><p>{item.overview || 'Ingen beskrivelse tilgængelig.'}</p></div><button disabled={!data?.canWrite || item.existing || Boolean(busy) || !connections[item.provider]?.rootFolderPath || !connections[item.provider]?.qualityProfileId} onClick={() => void add(item)}>{item.existing ? <CheckCircle2 /> : <Plus />}{item.existing ? 'Allerede tilføjet' : 'Tilføj og søg'}</button></article>)}</div>
      {!results.length && <div className={styles.empty}><Search /><strong>Find den næste film eller serie</strong><span>Resultater gemmes ikke i BoltBytes, før du aktivt vælger Tilføj.</span></div>}
    </section>
  </section>;
}

function ProviderCard({ provider, connection, form, libraries, resources, credentials, busy, canWrite, update, save, test, loadResources, rotate, remove }: { provider: Provider; connection: Connection | undefined; form: Form; libraries: Library[]; resources: Resources | undefined; credentials: Credentials | undefined; busy: string; canWrite: boolean; update: (provider: Provider, field: keyof Form, value: string | boolean) => void; save: (provider: Provider) => Promise<void>; test: (provider: Provider) => Promise<void>; loadResources: (provider: Provider) => Promise<void>; rotate: (provider: Provider) => Promise<void>; remove: (provider: Provider) => Promise<void> }) {
  const compatible = libraries.filter((library) => library.type === provider || library.type === 'mixed'); const origin = typeof window === 'undefined' ? '' : window.location.origin; const externalUrl = `${origin}${credentials?.webhookPath ?? connection?.webhookPath ?? ''}`;
  return <article className={styles.provider} data-provider={provider}><header><div className={styles.providerIcon}>{provider === 'sonarr' ? <Tv /> : <Film />}</div><div><span>{provider === 'sonarr' ? 'SERIEAUTOMATION' : 'FILMAUTOMATION'}</span><h2>{providerLabel(provider)}</h2><p>{connection?.health?.online ? `${connection.health.instanceName ?? connection.label} · v${connection.health.version ?? '?'}` : connection?.health?.error ?? 'Ikke forbundet'}</p></div><i data-online={connection?.health?.online}>{connection?.health?.online ? 'Online' : 'Offline'}</i></header>
    <div className={styles.form}><label>Server-URL<input disabled={!canWrite} value={form.url} onChange={(event) => update(provider, 'url', event.target.value)} placeholder={provider === 'sonarr' ? 'http://sonarr:8989' : 'http://radarr:7878'} /></label><label>API-nøgle<input disabled={!canWrite} type="password" autoComplete="off" value={form.apiKey} onChange={(event) => update(provider, 'apiKey', event.target.value)} placeholder={connection?.hasApiKey ? 'Gemt krypteret · lad stå tomt for at beholde' : 'Indsæt API key'} /></label><label>BoltBytes-bibliotek<select disabled={!canWrite} value={form.libraryId} onChange={(event) => update(provider, 'libraryId', event.target.value)}><option value="">Ingen automatisk scan</option>{compatible.map((library) => <option value={library.id} key={library.id}>{library.name}</option>)}</select></label><label className={styles.toggle}><input disabled={!canWrite} type="checkbox" checked={form.enabled} onChange={(event) => update(provider, 'enabled', event.target.checked)} /><span />Aktivér integration</label></div>
    {connection?.configured && <div className={styles.defaults}><div><Server /><strong>Servarr-defaults</strong><button onClick={() => void loadResources(provider)} disabled={Boolean(busy)}>Hent mapper og profiler</button></div>{resources && <><label>Root folder<select disabled={!canWrite} value={form.rootFolderPath} onChange={(event) => update(provider, 'rootFolderPath', event.target.value)}><option value="">Vælg mappe</option>{resources.rootFolders.map((folder) => <option value={folder.path} key={folder.id}>{folder.path}{folder.accessible ? '' : ' (ikke tilgængelig)'}</option>)}</select></label><label>Kvalitetsprofil<select disabled={!canWrite} value={form.qualityProfileId} onChange={(event) => update(provider, 'qualityProfileId', event.target.value)}><option value="">Vælg profil</option>{resources.qualityProfiles.map((profile) => <option value={profile.id} key={profile.id}>{profile.name}</option>)}</select></label><small>Kø: {resources.queue?.count ?? 0} · Ukendte: {resources.queue?.unknownCount ?? 0}</small></>}</div>}
    <div className={styles.actions}><button onClick={() => void test(provider)} disabled={!canWrite || Boolean(busy)}>{busy === `test:${provider}` ? <LoaderCircle className={styles.spin} /> : <RefreshCw />}Test</button><button className={styles.primary} onClick={() => void save(provider)} disabled={!canWrite || Boolean(busy) || !form.url}>{busy === `save:${provider}` ? <LoaderCircle className={styles.spin} /> : <CheckCircle2 />}Gem sikkert</button>{connection?.configured && <button aria-label={`Fjern ${providerLabel(provider)}`} className={styles.danger} onClick={() => void remove(provider)} disabled={!canWrite || Boolean(busy)}><Trash2 /></button>}</div>
    {connection?.configured && <div className={styles.webhook}><div><Webhook /><span><strong>Webhook efter import</strong><small>{connection.lastWebhook ? `${connection.lastWebhook.eventType}${connection.lastWebhook.title ? ` · ${connection.lastWebhook.title}` : ''} · ${new Date(connection.lastWebhook.receivedAt).toLocaleString('da-DK')}` : 'Ingen webhook modtaget endnu'}</small></span><button onClick={() => void rotate(provider)} disabled={!canWrite || Boolean(busy)}><KeyRound />{connection.hasWebhookSecret ? 'Rotér secret' : 'Opret secret'}</button></div>{credentials && <div className={styles.credentials}><p><b>URL</b><code>{externalUrl}</code><CopyButton value={externalUrl} /></p><p><b>Basic username</b><code>{credentials.username}</code><CopyButton value={credentials.username} /></p><p><b>Basic password</b><code>{credentials.password}</code><CopyButton value={credentials.password} /></p><small>Passwordet vises kun nu. Alternativt kan headeren <code>{credentials.headerName}</code> bruges.</small></div>}</div>}
  </article>;
}

function CopyButton({ value }: { value: string }) { return <button aria-label="Kopiér" onClick={() => void navigator.clipboard.writeText(value)}><Copy /></button>; }
function providerLabel(provider: Provider) { return provider === 'sonarr' ? 'Sonarr' : 'Radarr'; }
function failure(reason: unknown) { const item = reason as ApiFailure; return item?.message || 'Handlingen kunne ikke gennemføres.'; }
