import 'package:flutter/material.dart';

class TvDesignTokens {
  const TvDesignTokens._();

  static const double pageTitleSize = 38;
  static const double pageSubtitleSize = 13.5;
  static const double pageHeaderIconSize = 54;
  static const double contentPanelPadding = 20;
  static const double contentRailWidth = 272;
  static const double contentMaxWidth = 1440;

  static const Color background = Color(0xFF010204);
  static const Color backgroundWarm = Color(0xFF1B1207);
  static const Color surface = Color(0xFF06090D);
  static const Color surfaceRaised = Color(0xFF121A23);
  static const Color surfaceGlass = Color(0xE30A0F15);
  static const Color panelBorder = Color(0xFF344451);
  static const Color panelBorderSoft = Color(0x493C4B57);
  static const Color gold = Color(0xFFF2C765);
  static const Color goldSoft = Color(0xFFFFE7A0);
  static const Color cyan = Color(0xFF84DDFF);
  static const Color textMuted = Color(0xFFB4C0CA);
  static const Color focusFill = Color(0xFFFFE8A3);
  static const Color selectedFill = Color(0xFF2A210F);
  static const Color danger = Color(0xFFFF8F8F);

  static const double chromeRadius = 16;
  static const double panelRadius = 24;
  static const double pageHorizontalPadding = 36;
  static const double pageVerticalPadding = 14;
  static const double topRowHeight = 50;
  static const double topRowGap = 5;
  static const double sidebarCollapsedWidth = 54;
  static const double sidebarExpandedWidth = 164;
  static const double sidebarItemHeight = 36;
  static const double sidebarGap = 2;
  static const double heroHeight = 344;
  static const double heroContentWidth = 740;
  static const double detailHeroHeight = 320;
  static const double detailContentWidth = 960;
  static const double cardWidth = 132;
  static const double cardHeight = 248;
  static const double cardGap = 12;
  static const double sectionGap = 15;
  static const double sectionTitleSize = 18;
  static const double bodyTextSize = 14;
  static const double actionBarHeight = 50;
  static const double actionButtonHeight = 38;
  static const double focusBorderWidth = 2.25;
  static const double focusScale = 1.052;
  static const Duration focusAnimationDuration = Duration(milliseconds: 155);
  static const Duration pageAnimationDuration = Duration(milliseconds: 260);
  static const int maxSectionItems = 22;
  static const int maxGenreItems = 20;
  static const double genreChipHeight = 74;
  static const double episodeTileHeight = 104;
  static const double profileCardWidth = 204;
  static const double profileCardHeight = 236;
  static const double epgHalfHourWidth = 146;
  static const double epgChannelWidth = 210;
  static const double epgRowHeight = 64;
  static const double playerControlHeight = 46;
  static const double playerDeckMaxWidth = 1120;
  static const double playerDeckRadius = 20;
  static const double playerTimelineHeight = 8;
  static const double playerControlSize = 42;
  static const double playerPrimaryControlSize = 52;
  static const Color luxuryGold = Color(0xFFFFD978);
  static const Color luxuryIce = Color(0xFF8EDCFF);
  static const Color luxurySurface = Color(0xE611171E);
  static const Color luxurySurfaceRaised = Color(0xF21A222C);
  static const Duration luxuryFocusDuration = Duration(milliseconds: 150);
  static const Duration luxuryRevealDuration = Duration(milliseconds: 420);
  static const double luxuryFocusLift = 6;
  static const int actionSectionIndex = 900;
}
